### ISSUE TITLE
Offer logo for Stamp

### ISSUE THREAD

**Issue by familqasimov** [sjnyag/stamp#116]
Hi sir. I'm graphic designer. I have studied your work and I think a new design will make you more visible. I would like to offer logo. I can give you all the formats of the design free. If you want I send you PR or a change please specify.

![untitled-1](https://user-images.githubusercontent.com/36432269/39410012-c7d4f586-4c01-11e8-95d9-053cf4bb5edc.png)

## Logo idea
A simple logo with the form play marks and reminiscent of the letter S in the stamp

![black](https://user-images.githubusercontent.com/36432269/39410013-cceb3490-4c01-11e8-9708-652d0313bf01.png)

Best regard
Famil Qasimov

**Comment by familqasimov** [comment]
Hi sir. So I changed my logo. I hope you like it.

![untitled-1](https://user-images.githubusercontent.com/36432269/39414206-0fc9878c-4c46-11e8-9f39-c358034fd302.png)

**Comment by sjnyag** [comment]
Thank you for fixing!
The new icon is closer to my ideals!
Also, I want to display the banner on the Play Store.

Both icon and banner are already at a level that I can not make, however, can you make it a simple and friendly design rather than a cool one?
The simple and friendly design I think is as follows.

![nexus2cee_ic_launcher_calculator_round_thumb](https://www.androidpolice.com/wp-content/uploads/2016/09/nexus2cee_ic_launcher_calculator_round_thumb.png)
![nexus2cee_product_logo_keyboard_stylus_round_launcher_color_48_thumb](https://www.androidpolice.com/wp-content/uploads/2016/09/nexus2cee_product_logo_keyboard_stylus_round_launcher_color_48_thumb.png)

[Pixel Launcher Sneak Peek Part 1: Google's new circular launcher icons [APK Teardown]](https://www.androidpolice.com/2016/09/20/pixel-launcher-sneak-peek-part-1-googles-new-circular-launcher-icons-apk-teardown/)

Sincerely

**Comment by familqasimov** [comment]
Hi sir Iook product icon design is inspired by the tactile and physical quality of material. Maybe I tried to make a shadow effect like the shadow of every object. I tried to make the original shade of the sunshine. I hope you are like it.

![2](https://user-images.githubusercontent.com/36432269/39487259-a6ca6936-4d8f-11e8-8bdc-d9f6c82872bb.png)

**Comment by sjnyag** [comment]
Thank you very much!
Thank you for listening to my request!
Yes! This is my ideal! Very very nice!

It is sufficient as it is, however if it's possible, I would like to ask you to make small revisions about Shadows and Edge tint and shade according to guideline ([Icons - Style - Material Design](https://material.io/guidelines/style/icons.html#icons-icons-for-android)).

I want you to try these 4 points.
1. Change shadow angle to 45º and extend shadow length to the foreground boundary with gradation.
2. Create contact shadows.
3. Highlight the top edge of elements(Tinted edges). 
4. Apply dark bottom edges to elements(Shaded edges).

<img width="1296" alt="2018-05-02 10 16 36" src="https://user-images.githubusercontent.com/18021730/39500787-f76b0b36-4df1-11e8-86e7-8be95db6edc9.png">
<img width="1290" alt="2018-05-02 9 46 08" src="https://user-images.githubusercontent.com/18021730/39500788-f792430e-4df1-11e8-926c-f6433ed807f0.png">

Thank you as always.
Sincerely

**Comment by familqasimov** [comment]
![00](https://user-images.githubusercontent.com/36432269/39505953-c9495c22-4de6-11e8-90e9-1120784be503.png)

**Comment by familqasimov** [comment]
I want create a pull request with new logo but dont remove old logo on the priview changes. I upload all file (.png) with sizes to the directory is stamp/app/src/main/res/mipmap.
I also add there black and white logo.

**Comment by sjnyag** [comment]
Thank you for your pull request!
It was merged.

Thank you for letting me have a valuable experience.

**Comment by familqasimov** [comment]
hello Mr. sjnyag. Do not you like the logo? I was really glad to work on this together. but I see that you have erased it. Unfortunately, I shared this project as my successful works.

**Comment by sjnyag** [comment]
Sorry, there are 2 problems for update, so temporarily rolled back the icon.
1. The icon appears choppy on the status bar.
![2018-05-13 18 13 26](https://user-images.githubusercontent.com/18021730/39965722-6915f68e-56d9-11e8-9b34-c152e41ae7fd.png)

2. Banner image should be 1,024 x 500 for Google Play.

So, I'm trying to fix icon image by myself.
I want to prepare icon edit environment for not only current problems but also future maintenance.
